### ISSUE TITLE
Vlaječka se trochu opakuje na monitoru se scale faktorem 1.25

### ISSUE THREAD

**Issue by FilipChalupa** [podlomar/kodim.cz#13]
## Teď

![image](https://user-images.githubusercontent.com/1045362/159056360-325591c5-2212-4eea-91a6-89c0eb1479be.png)

## Navrhovaná oprava

```css
.term__flag {
    background-repeat: no-repeat;
}
```

![image](https://user-images.githubusercontent.com/1045362/159056452-959f8f48-3308-4601-906b-4d6698fc4943.png)

![image](https://user-images.githubusercontent.com/1045362/159056476-abd83b26-5b02-454d-8b2d-e27152f82f22.png)
